import type { Metadata } from "next";
import "@example/scss/index.scss";
import { GoogleTagManager } from '@next/third-parties/google'
import ThemeClientProvider from "@/app/ThemeClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isProduction = process.env.NEXT_PUBLIC_ENV === "production"
  const checkGTM = process.env.NEXT_PUBLIC_GTM
  const GTM_ID = process.env.NEXT_PUBLIC_GTM_ID

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeClientProvider>
          {children}
        </ThemeClientProvider>
      </body>
      {isProduction &&
        <>
          {(checkGTM && GTM_ID) &&
            <GoogleTagManager gtmId={GTM_ID} />
          }
        </>
      }
    </html>
  );
}